#! /bin/sh
sudo chmod 777 *;
sleep 1;
sudo mkdir /accesscontrol;
sleep 1;
sudo cp -r ./backend /accesscontrol/backend;
sleep 1;
sudo cp -r ./frontend /accesscontrol/frontend;
sleep 1;
sudo cp -r ./backend.service /usr/local/bin/backend.sh;
sudo chmod +x /usr/local/bin/backend.sh;
sleep 1;
sudo cp -r ./backend.service /usr/local/bin/rfidentrance.sh;
sudo chmod +x /usr/local/bin/rfidentrance.sh;
sleep 1;
sudo cp -r ./backend.service /usr/local/bin/rfidexit.sh;
sudo chmod +x /usr/local/bin/rfidexit.sh;
sleep 1;
sudo systemctl daemon-reload;
sleep 1;
sudo systemctl enable backend.service;
sleep 1;
sudo systemctl start backend.service;
sleep 1;
